//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBIMCA.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tooltips() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBIMCA.Resources.Files.Tooltips", typeof(Tooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Tools relating to cleaning the model.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deletes all Fill and Line Patterns found in the current document that begin with the word &apos;Import&apos;.
        ///
        ///Condition(s) to run:
        ///- The current document is a project or family
        ///
        ///Warning:
        ///This tool will not provide a list to choose from - it will go straight to deletion.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Audit_DeletePatterns {
            get {
                return ResourceManager.GetString("Audit_DeletePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provides a list of all unused View Filters in the current document, from which you can choose which ones to delete from the model.
        ///
        ///Condition(s) to run:
        ///- The current document is a project
        ///
        ///Note:
        ///This tool will check all Views and View Templates for used filters.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Audit_PurgeFilters {
            get {
                return ResourceManager.GetString("Audit_PurgeFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provides a list of all unplaced rooms in the current document, from which you can choose which ones to delete from the model.
        ///
        ///Condition(s) to run:
        ///- The current document is a project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Audit_PurgeRooms {
            get {
                return ResourceManager.GetString("Audit_PurgeRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provides a list of all unused View Templates in the current document, from which you can choose which ones to delete from the model.
        ///
        ///Condition(s) to run:
        ///- The current document is a project
        ///
        ///Note:
        ///This tool will check all Views and View Family Types for assigned and default templates.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Audit_PurgeTemplates {
            get {
                return ResourceManager.GetString("Audit_PurgeTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools relating to  exporting data from Revit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exports the contents of the active schedule view to Excel.
        ///
        ///Condition(s) to run:
        ///- Current view is a schedule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Export_Schedule {
            get {
                return ResourceManager.GetString("Export_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exports selected sheets from Revit to DWG, using internal coordinates.
        ///
        ///Condition(s) to run:
        ///- The current document is a project
        ///
        ///Notes:
        ///The tool will apply a generic naming rule to exported documents.
        ///
        ///Shift + click:
        ///Uses shared coordinates instead.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Export_SheetsDwg {
            get {
                return ResourceManager.GetString("Export_SheetsDwg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exports selected sheets from Revit to PDF.
        ///
        ///Condition(s) to run:
        ///- The current document is a project
        ///
        ///Notes:
        ///The tool will apply a generic naming rule to exported documents. The built-in Pdf exporter is used for the exporting process, which automatically detects page sizes.
        ///
        ///Shift + click:
        ///Shows crop boundaries (hidden by default).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Export_SheetsPdf {
            get {
                return ResourceManager.GetString("Export_SheetsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools relating to importing information to Revit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using the templated Excel file, creates new sheets and updates the names of existing ones provided.
        ///
        ///Condition(s) to run:
        ///- The current document is a project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Import_CreateSheets {
            get {
                return ResourceManager.GetString("Import_CreateSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saves a template for entering sheet information that can be imported back into Revit.
        ///
        ///Condition(s) to run:
        ///- The current document is a project
        ///
        ///Shift + click:
        ///Exports all sheet names and numbers to the template.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Import_SheetsExcel {
            get {
                return ResourceManager.GetString("Import_SheetsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools relating to revision management.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds a chosen revision to sheets, selected from a list. If the revision is already applied to a sheet, it will skip that sheet.
        ///
        ///Condition(s) to run:
        ///- Current document is a project
        ///
        ///Shift + click:
        ///Removes the chosen revision instead.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Revision_BulkRev {
            get {
                return ResourceManager.GetString("Revision_BulkRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Given chosen revisions and sheets, will generate an Excel based document transmittal (&apos;doctrans&apos;) that summarizes the revision numbers on those sheets.
        ///
        ///Condition(s) to run:
        ///- Current document is a project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Revision_DocTrans {
            get {
                return ResourceManager.GetString("Revision_DocTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Given a chosen revision, creates a new sheet set for all sheets with that revision.
        ///
        ///Condition(s) to run:
        ///- Current document is a project
        ///
        ///Note:
        ///If the sheet set already exists, it will be deleted and re-created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Revision_RevSet {
            get {
                return ResourceManager.GetString("Revision_RevSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools relating to selection tasks.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enables reveal hidden elements mode, then selects any elements that are hidden in the active view.
        ///
        ///Condition(s) to run:
        ///- The current document is a project.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_GetHidden {
            get {
                return ResourceManager.GetString("Select_GetHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For all currently selected sheets, will in turn select any titleblock(s) on them.
        ///
        ///Condition(s) to run:
        ///- Sheets are selected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_GetTtbs {
            get {
                return ResourceManager.GetString("Select_GetTtbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puts Revit into a mode where you can only select rooms.
        ///
        ///Condition(s) to run:
        ///- The current document is a project.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_PickRooms {
            get {
                return ResourceManager.GetString("Select_PickRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Puts Revit into a mode where you can only select walls.
        ///
        ///Condition(s) to run:
        ///- The current document is a project.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_PickWalls {
            get {
                return ResourceManager.GetString("Select_PickWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removes any grouped elements (and groups) from the current selection.
        ///
        ///Condition(s) to run:
        ///- Elements are selected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Select_RemoveGrouped {
            get {
                return ResourceManager.GetString("Select_RemoveGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggles the Warden feature.
        ///
        ///Warden is a simple command interceptor, which will verify if you want to use bad practice commands before they execute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Settings_Warden {
            get {
                return ResourceManager.GetString("Settings_Warden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools relating to worksets.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Workset {
            get {
                return ResourceManager.GetString("Workset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creates worksets from a fixed standard, chosen from a list of names.
        ///
        ///Condition(s) to run:
        ///- The current document is a project
        ///- The current document is workshared
        ///
        ///Notes:
        ///The tool will offer to rename the &apos;Shared Levels and Grids&apos; workset if it is found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Workset_Create {
            get {
                return ResourceManager.GetString("Workset_Create", resourceCulture);
            }
        }
    }
}
